### ISSUE TITLE
Make default browse location for Welcome screen be more appropriate.

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#100]
Instead of having the default location be "My Computer", we should set it to be something more appropriate like "My Documents".

**Comment by yyoon** [comment]
For me, it does that already, as shown below.
![image](https://cloud.githubusercontent.com/assets/1309817/9001416/26ef3f7c-3792-11e5-842e-796dacee243a.png)

Or, did you want something else, for example the "My Documents" folder being expanded initially?

**Comment by sguergachi** [comment]
Yeah. This was a piece of feedback I got and I think it makes sense. Very few people would put their journals in any folder in My Computer other than My Documents right? It will either most likely be in My Documents or Dropbox. Anywhere else can be navigated to.


-
Sammy Guergachi

**Comment by yyoon** [comment]
I'm not sure if I understand. The current default location is already My Documents, not My Computer. What exactly are you suggesting?

**Comment by sguergachi** [comment]
Sorry, I meant it should be expanded.


-
Sammy Guergachi

**Comment by yyoon** [comment]
Okay. I'll see if I can do that.

**Comment by yyoon** [comment]
Unfortunately, the `FolderBrowserDialog` that we're using doesn't seem to provide a way to fine-control the tree view area. We could roll our own version of `FolderBrowserDialog` with full control, but it would be an overkill.

**Comment by sguergachi** [comment]
Ok. Close this for now then.


-
Sammy Guergachi
