### ISSUE TITLE
Feature request: Portable exe

### ISSUE THREAD

**Issue by erdihu** [yyoon/Journaley#105]
Thanks for this wonderful application. Is it possible to have it on flash drive as a portable app?

**Comment by yyoon** [comment]
It is sort of possible, and you can do so by copying all the files from %LOCALAPPDATA%\Journaley\app-2.1\ to a folder in your flash drive.

This will have at least two problems, though.
- The settings file won't be saved on your flash drive, so you will have to go through the initial set up steps (the welcome screen) every time you launch Journaley on a new computer.
- The auto-update feature won't work.

**Comment by sguergachi** [comment]
@yyoon I think if more people request this we should make a portable version (without the updating). Would there be a problem with storing the settings file in the same directory as the executable?

**Comment by yyoon** [comment]
@sguergachi For the normal version (with updating), yes, there would be a problem because the directory containing the executable changes upon update. If we make a portable version, it would not be difficult to make it save the settings file to the same folder.

**Comment by erdihu** [comment]
Closing the issue as the project is dormant.
