### ISSUE TITLE
12/24 hours option

### ISSUE THREAD

**Issue by erdihu** [yyoon/Journaley#106]
For some reason I can not bring the date to 24 hours mode when writing an entry. It would be very nice if implemented.

**Comment by yyoon** [comment]
Are you talking about the time displayed on the left panel below the date?
@sguergachi Do you have any opinion on this?

**Comment by erdihu** [comment]
I am talking about the time displayed on top of text input screen.

**Comment by sguergachi** [comment]
@erdihu is your system set to show time in 24 hour format? If so, I'm curious to see if the date/time api lets us know about that system setting so we can respect it in Journaley. I'm reluctant to add that as a setting. 

But it has to be consistent, everywhere time is displayed has to be the same format.

**Comment by erdihu** [comment]
Yes, my system is set to 24 hours format.

2015-08-12 14:56 GMT+02:00 Sammy Guergachi notifications@github.com:

**Comment by yyoon** [comment]
We do follow the system setting when determining whether the starting day of week is Monday or Sunday. We could also follow the system settings for the 12/24 hour format.

**Comment by erdihu** [comment]
Closing the issue as the project is dormant.
