### ISSUE TITLE
Improve first run experience

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#11]
When first starting up Journaley, the experience should be much smoother and welcoming. 

More details on specifically what can and should be done to improve this to come as we near completion.

**Comment by sguergachi** [comment]
Doesn't seem to be detecting my dropbox folder. What are you using to detect it?

**Comment by yyoon** [comment]
I'm using the method described here, which works fine for me.
http://stackoverflow.com/a/18426357/922135

Can you see the host.db file under %APPDATA%\Dropbox\host.db?
What does the file contain, when you open it with notepad, for example?

**Comment by sguergachi** [comment]
Can't find that file

**Comment by sguergachi** [comment]
it's located in C:\Users\Sammy\AppData\Local\Dropbox\ for me

**Comment by yyoon** [comment]
Okay. Seems like I should look for either %APPDATA%\Dropbox or %LOCALAPPDATA%\Dropbox.

**Comment by yyoon** [comment]
I added some code to look for the local app data folder, too (713ab247eb891431aac52a43208f719c93cee21b). Can you try it again?

**Comment by yyoon** [comment]
The main app now launches behind the last screen of the welcome UI, as you suggested. Let me know if it works as you expected.

**Comment by sguergachi** [comment]
We need to add a "Go Back" button in the Password Setup screen that goes back to previous screen in case you change your mind on adding a password. 

Updated WelcomeUI Storyboard to reflect this. The password fields should be made slightly thinner (smaller font) to accommodate the extra button.
