### ISSUE TITLE
Any security issues?

### ISSUE THREAD

**Issue by TheSacredSoul** [yyoon/Journaley#110]
First of all, a big thank you for developing this and for making it free. Day One not having a Windows version was seriously limiting my entries since I am hardly on my Mac and I don't like to type long entries on my phone.

I understand the data Day One backsup to DropBox is not encrypted. And since Jornaley is reading this data, is there anyway these data can be sent back to a home server? Or am I being paranoid over nothing? Just being cautious as journals, by definition, are very private things.

**Comment by yyoon** [comment]
First of all, it's my pleasure to hear that Journaley meets your needs.

I understand your privacy concern, and I assure you that Journaley does not do anything suspicious such as sending your private journals to someone else. It's very difficult to prove this to you, but what I would like to emphasize is that Journaley is 100% open source software. You can read the source code and verify that the program is not doing anything fishy, if you are a programmer. The only network traffic Journaley generates is when Journaley checks for its updates.

Hope this answer helps.

**Comment by TheSacredSoul** [comment]
Thank you! That's all I needed, just a confirmation from the dev. 

Thanks again for the awesome application!

**Comment by yyoon** [comment]
You're welcome! Feel free to give us other feedback and suggestions in the future.
