### ISSUE TITLE
Spell check for another lang.

### ISSUE THREAD

**Issue by Grokon** [yyoon/Journaley#111]
Hello, how can I add spell check for another lang? I need to add - "ru".

**Comment by sguergachi** [comment]
Unfortunately the spell check built into the text component that Windows provides for us only supports the languages you see in that list. If we find a different text entry component with more languages (or if Windows updates to supports more languages) we will make sure to implement that into the app.

## 

Sammy Guergachi

**Comment by Grokon** [comment]
Maybe need using language support pack  for .net components? 
Also I have question or idea about sync. Can you add sync options? And change options when used journal files to sync, not to block or cached use. Example: how it can work in dayone. I use DayOne on my mac, jrnl on command line (nix and etc.) and now I try to use Journaley on windows. I will be very happy when I find it and big thx for you work. Now I created sync folder with my all env. And if I add new data with DayOne or jrnl or Journaley after finished folder sync (1-2 sec) I see new data in DayOne and jrnl, but I need restart Journaley to see updated data. Now I use bittorrent sync for folder - this is not best choose, but I can't do it with icloud (on windows dayone.journal not synced).

P.S. sorry for my eng. And I don't know where I can post this problems.

**Comment by yyoon** [comment]
Unfortunately, the language support pack doens't add the spellcheck feature for that language.

Regarding the sync option, I think you're asking to make Journaley to monitor the sync folder and automatically display new entries that were added by Day One or jrnl, correct? I'm not sure why it would not be working in your environment, but the feature is already implemented in Journaley. When I keep Journaley open and add a new entry from Day One, then the entry soon appears in Journaley.

Is there any chance that you're sync folder is in a network drive or somewhere that is not a normal disk?

**Comment by Grokon** [comment]
That's right I need monitor entries in journal folder and show new in program if has update in another place.  My Sync folder located on drive C (C:\Users\grok\Sync) and I'm not using network drive or net folders. 
And also one example: I'll added 3 entries:
1. In Journaley on this date and put it:  "one"
2. After sync folder complete  - I'll seen this entries in DayOne and add new - "two"
3. In Journaley I don't see any changed and add new - "three". After sync - in DayOne I see it (no need reopen).
4. Now I restart Journaley and see all 3 entries and It's good, but I can't see it without program restart. This not big problem because all entries are saved , but If I don't need restart the program - It's be cool. Maybe need add "upd or sync" button for this.
Also when I writing this - I have arise a new Idea: add tray icon with quick add entries - how it has in DayOne, but maybe need another way: minimize Journaley in tray and add setting options "starting with windows in tray mode" and add global key to open program in "add entries window" or any else.
I don't know .Net, but I will be happy with any help. I can translate interface on russian lang if it need or maybe need another help.

And also please provide me name of spell checking library and link to it if it possible.

**Comment by sguergachi** [comment]
With regards to your idea for adding a tray icon to allow for quick entry. At this point we have quick shortcuts if you right click on the Journaley shortcut on the taskbar in Win 7 and up to create a New Entry. I'm unsure about whether adding another icon to my tray (which is already full) is a good idea. If you still think so please make a new issue for it so we can discuss further.

## 

Sammy Guergachi

**Comment by yyoon** [comment]
@Grokon I understand the sync issue, and it is already implemented. If it doesn't work, then it's a bug. Which version of Journaley are you using?

**Comment by Grokon** [comment]
I use Journaley v 2.1

**Comment by sguergachi** [comment]
Please create another issue for this problem. As for this issue, the matter is considered closed.
