### ISSUE TITLE
Nested List CSS

### ISSUE THREAD

**Issue by minchinweb** [yyoon/Journaley#114]
First off, awesome app!

I think something is off with the CSS applied to nested lists: even time the level increases, blank lines are added above first list item, with the number of lines determined by the indent level.

Let me give an example. This entry:

``` markdown
 Test Entry

- first level
- another
    - second level (4 spaces)
    - more second level
- first level
    - second level
        - third level (8 spaces)
             - fourth level (12 spaces)
- first level

regular text
```

is rendered as:

![image](https://cloud.githubusercontent.com/assets/1548809/10295456/f91ca51a-6b7d-11e5-88a8-b2fc971f49b4.png)

I would expect something much closer to how Github renders Markdown (without the extra lines).

The same text as above:

---

 Test Entry
- first level
- another
  - second level (4 spaces)
  - more second level
- first level
  - second level
    - third level (8 spaces)
      - fourth level (12 spaces)
- first level

regular text

**Comment by sguergachi** [comment]
Yeah I've known about this, just haven't had time to fix it. I'm going to try and use Git Hub's way of rendering this since it seems to work and look good.

**Comment by crxtrdude** [comment]
Yeah, I think you guys need to use something similar to Github's CSS as Day One does use the GFM and it could be nice if the rendering would look similar.

**Comment by sguergachi** [comment]
Any idea where the github markdown CDs styling is?
- Sammy Guergahchi

**Comment by sguergachi** [comment]
Sorry meant *css
- Sammy Guergahchi

**Comment by crxtrdude** [comment]
I really don't know to be honest, but a google search did lead me to the following:

[Github.CSS by Andy Ferra](https://gist.github.com/andyferra/2554919)
[Sindresorhus' github-markdown-css](https://github.com/sindresorhus/github-markdown-css)

The latter claims to be 'minimal'. I checked also the CSS, it has an embedded webfont included.
Andy's CSS has no embedded webfont.

**Comment by sguergachi** [comment]
Looking at view source shows the issue isn't css, the generated html is filled with break tags for some reason:
![image](https://cloud.githubusercontent.com/assets/615386/11248732/c650736a-8df0-11e5-93a6-59e1cf3f948f.png)

**Comment by crxtrdude** [comment]
If those are not the case, it's the fault of MarkdownSharp, since it's the one who interpret the Markdown and  converting to html tags.

**Comment by sguergachi** [comment]
Do you think you can test the markdown from the original post and test it with sundown markdown processor? See if the html is different.

**Comment by crxtrdude** [comment]
I don't have sundown specifically, but I got the closest (Hoedown for C included in CuteMarkEd):

```
</head>
<body>
<p>Test Entry</p>

<ul>
<li>first level</li>
<li>another

<ul>
<li>second level (4 spaces)</li>
<li>more second level</li>
</ul></li>
<li>first level

<ul>
<li>second level

<ul>
<li>third level (8 spaces)

<ul>
<li>fourth level (12 spaces)</li>
</ul></li>
</ul></li>
</ul></li>
<li>first level</li>
</ul>

<p>regular text</p>
```

There is a Hoedown [wrapper](https://github.com/tobiasviehweger/hoedown.net) for .NET as well.

**Comment by sguergachi** [comment]
Ok, I stripped break tags at `UpdateWebBrowser()` and got the desired result:
![image](https://cloud.githubusercontent.com/assets/615386/11249386/74ea68a6-8df4-11e5-89ad-b5bf9fb890e7.png)

**Comment by minchinweb** [comment]
Deleting `<br>` tags wholesale will likely cause other issues. For example, the following Markdown should be on two lines:

```
Two spaces at the end of this line  
mean this is rendered as two lines
```

[That said, GitHub purposely breaks this rendering to put them on separate lines.]

As well, Markdown accepts raw HTML, so what happens to `<br>` in the middle of Markdown entries?

Perhaps the solution is to only filter `<br />` following `</li>`?

**Comment by sguergachi** [comment]
That's what I'm looking at doing. In anycase filtering break tags would be a hack. We should be looking at the source of the problem being the input we give to `Markdown.Transform()`.

**Comment by sguergachi** [comment]
Ok here is the fix, should not affect anything other than unordered lists.
https://github.com/yyoon/Journaley/commit/13b8b9317a0c26cdad5d347969359f258875c5af
@yyoon will probably find a better solution to this, so it's in a separate branch for now.

**Comment by yyoon** [comment]
Can you make a PR for this? I'll make some comments on the PR.

**Comment by sguergachi** [comment]
Done: https://github.com/yyoon/Journaley/pull/125
