### ISSUE TITLE
Searching entries by text

### ISSUE THREAD

**Issue by yyoon** [yyoon/Journaley#117]
Suggested by a user:

> Suggestion (that would make it useful for me): have the ability to text search the entries.
> For example, I have journal entries about the various parks I've visited and have created the tag "Parks." What I would like to have is the ability to do an ad-hoc search for the name of a specific park without having to look at all the entries. This type of ad-hoc searching is a one-off search so I don't want to create a tag for each park mentioned in an entry as the tag list would quickly become unwieldy.

**Comment by sguergachi** [comment]
This issue was already created in 76

**Comment by sguergachi** [comment]
https://github.com/yyoon/Journaley/issues/76
