### ISSUE TITLE
Words wont show up on the entry page on Windows 8

### ISSUE THREAD

**Issue by purplemoonmyst** [yyoon/Journaley#121]
when I try and write a entry the words wont show up on the entry page.

**Comment by sguergachi** [comment]
Just to be clear, you pressed the "+" button and then when you clicked on the entry area do you see a blinking I beam?
- Sammy Guergahchi

**Comment by purplemoonmyst** [comment]
nope... nothing..

[image: photo]
_Hillary Roberts_
Freelance Copywriter/Blogger/Writer
Hillary@hillarynicoleroberts.com | www.hillarynicoleroberts.com | Skype:
purplemoonmyst <#>
http://www.facebook.com/HillaryNicoleroberts
http://twitter.com/hillarynroberts
http://www.pinterest.com/purplemoonstar/
http://instagram.com/purplemoonmyst/
Hillary Nicole Roberts My Fall Freelancing Goals
http://feeds.feedblitz.com/~/122025286/0/hillarynicoleroberts~My-Fall-Freelancing-Goals/
✔ Get a Signature like this: Click Here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MTIwJnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MTM1NzMyNTA1OTY4NjQiLCAiZSI6ICI1NzEzNTczMjUwNTk2ODY0In0=

**Comment by sguergachi** [comment]
Alright, sorry for the troubles then.
Can you updated to the latest .NET package from here: https://www.microsoft.com/en-us/download/details.aspx?id=48130
We are using a special spell checked text field which might not be on your system, so hopefully if that's the issue this might solve it.

Thanks

**Comment by yyoon** [comment]
@purplemoonmyst Also, could you tell us what version of Windows you are using?
That might help diagnosing the problem.

**Comment by yyoon** [comment]
Sorry, I missed that Windows 8 part on the title. It should work fine on Windows 8.
Can you please check if `error.log` file is generated?
Try Windows+R -> Type in "%APPDATA%\Journaley\error.log".
![image](https://cloud.githubusercontent.com/assets/1309817/11108527/45b09130-889c-11e5-9ea2-70c2c96c06db.png)

This command will show you the contents of the file, if it is generated.
If so, paste the contents here would help a lot in figuring out the problem.

**Comment by purplemoonmyst** [comment]
I am not sure how but it magically started working. Thanks for all your
help!

[image: photo]
_Hillary Roberts_
Freelance Copywriter/Blogger/Writer
Hillary@hillarynicoleroberts.com | www.hillarynicoleroberts.com | Skype:
purplemoonmyst <#>
http://www.facebook.com/HillaryNicoleroberts
http://twitter.com/hillarynroberts
http://www.pinterest.com/purplemoonstar/
http://instagram.com/purplemoonmyst/
Hillary Nicole Roberts My Fall Freelancing Goals
http://feeds.feedblitz.com/~/122025286/0/hillarynicoleroberts~My-Fall-Freelancing-Goals/
✔ Get a Signature like this: Click Here!
http://ws-promos.appspot.com/r?rdata=eyJydXJsIjogImh0dHA6Ly93d3cud2lzZXN0YW1wLmNvbS9lbWFpbC1pbnN0YWxsP3dzX25jaWQ9NjcyMjk0MTIwJnV0bV9zb3VyY2U9ZXh0ZW5zaW9uJnV0bV9tZWRpdW09ZW1haWwmdXRtX2NhbXBhaWduPXByb21vXzU3MTM1NzMyNTA1OTY4NjQiLCAiZSI6ICI1NzEzNTczMjUwNTk2ODY0In0=

**Comment by sguergachi** [comment]
Good to know! Let us know if you have any other issues.
