### ISSUE TITLE
Export Journal to Cloud Provider (Google, MS OneDrive etc)

### ISSUE THREAD

**Issue by AdamFx** [yyoon/Journaley#122]
Hello. Thanks for your product. I am a daily user. 
I would like to export the Journal or time selected journal entries to a Word Processor. 
Could an Export feature to Cloud providers be incorporated - Date/Time heading, image, text and tags in chronological/reverse chronological order.

Thanks for the great product.

**Comment by sguergachi** [comment]
We are planning on implementing this. Checkout #75 to give your input as we decide how to implement this.
