### ISSUE TITLE
Adding a Starred View aside from timeline, calendar and tag views

### ISSUE THREAD

**Issue by crxtrdude** [yyoon/Journaley#123]
Apparently in Day One, you have the _star_ button which lets you flag an entry as **Starred**, similar to sticky-ing a post in a forum. You already implemented a _star_ button, but without the **Starred** category it kind of defeats the purpose of the _star_ button.

Since I saw on most posts that I have, it does recognize the **Starred** entries, so I don't think it's that hard to add onto a view for that.

Sorry if someone already added this or is on the works now, Just wanting to let you guys know.

**Comment by sguergachi** [comment]
Are you asking about being able to see just _starred_ entries? That's possible, since starred entries are tagged and can be found by going to the Tag tab in the bottom left then selecting the **Starred** tag, the entries you starred should be shown below.

**Comment by crxtrdude** [comment]
Oh, okay. Got you on that one, but it's nice to have a button like in Day One, instead of going an extra step to see those

Or the current method is a design choice on you guys?

**Comment by sguergachi** [comment]
Not a design choice just missing currently, filtering by date or started/not-started might come with search implementation https://github.com/yyoon/Journaley/issues/76

**Comment by crxtrdude** [comment]
Oh, okay, I've watched the project now in case this would be solved. I'll close this for now. Thanks Sammy.

**Comment by crxtrdude** [comment]
BTW, I've actually [done some](https://github.com/crxtrdude/pyJournalLier) Day One stuff as well, but for Python (based on [pyDayOne](https://github.com/nitinthewiz/pyDayOne)) so I'm surprised that this still keeps on going despite other's efforts in making a Day One compatible app for Windows.
