### ISSUE TITLE
Timeline - Title with a period is considered a first sentence instead of a title.

### ISSUE THREAD

**Issue by crxtrdude** [yyoon/Journaley#126]
Supposed a entry like this.

```
This is my sentence.

I have been happy that I would be ....
```

It should be in the timeline like this:

> **This is my sentence**
> I have been happy that I would be ...

But instead it treats it as a first sentence like this:

> This is my sentence.

In Day One in fact, if it's the first sentence, it will always be the title, with or without whitespace below it.

Sample:

```
Nikki 1.
Nikki 2.
```

Day One displays it like:

> **Nikki 1**
> Nikki 2.

If it's intentionally like that, it's fine by me, but aesthetic wise, it would be nice to consider.

**Comment by sguergachi** [comment]
Well, if you remove the period, which makes the title a sentence and not a title then it looks like this:
![image](https://cloud.githubusercontent.com/assets/615386/11308421/3299a798-8f8c-11e5-95fd-b647b8a25ffe.png)

What's the thinking behind a title with a period at the end being automatically considered a title and not a sentence? From my point of view, I start a lot of entries with a sentence and rarely with titles. So being explicit in the writing of whether you want a title or a sentence is the best course of action than assuming all first sentences are titles.

**Comment by crxtrdude** [comment]
Well, it does seem like a good point though. I'm fine with that. It defeats the logic of first sentncing for that matter.

What abou if the title uses ellipses (...) sometimes i use that kind of title as well

**Comment by sguergachi** [comment]
I think that can be an exception that should be made to https://github.com/yyoon/Journaley/issues/17
I have other issues I'd like to make to it anyways.
