### ISSUE TITLE
Clicking on a Markdown link should open the link in users default browser

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#131]
Right now clicking on a markdown enabled URL opens the website inside the Journaley web view. This should not be the case, instead the users default browser (preferably) should handle the URL.

**Comment by crxtrdude** [comment]
I currently have the solution to that problem actually. I've seen a fix for the WebBrowser control and I've actually implemented it during the time I edited MarkdownDeep. But when I changed my Git GUI from Git Ext to SourceTree, the changes were gone. I might implement this.
