### ISSUE TITLE
Narrate is now open source

### ISSUE THREAD

**Issue by crxtrdude** [yyoon/Journaley#140]
Just recently I updated my phone's apps and then I checked back Narrate's settings again. I noticed that a little disclaimer is included in the copyright:

"Narrate is an open source project licensed under Apache 2.0 and hosted on Github."

Then I checked over the play store and noticed a link which explains the reason of putting the source open.

[I Just Open Sourced My Most Popular Android App | Timothy Miko](http://timohty.com/i-just-open-sourced-my-most-popular-android-app/)

The github project is https://github.com/timothymiko/narrate-android

---

In another note, I guess we need to update the site to say narrate and day one classic is the ones supported (or something like that)

**Comment by sguergachi** [comment]
This is nice for Narrate but I don't see how this is an issue for Journaley. 

Regarding adding the fact we support Narrate to the website, that would technically be inaccurate. Narrate and Journaley both support Day One, there's no specific support for Narrate in Journaley.

**Comment by crxtrdude** [comment]
I know that, I just want to let you guys know regarding this, since the fact that the one that we supported, Day One, is going more and more proprietary with their app, although come to think of it, maybe they use the same format anyway. I'll just close this one to spare you the trouble

**Comment by sguergachi** [comment]
Yeah, I'm pretty sure they basically do the same thing we do to support Day One, just parse the Day One entry files.
