### ISSUE TITLE
Journaley font display is illegible

### ISSUE THREAD

**Issue by CraigRLang** [yyoon/Journaley#149]
I noted that on my Windows 8.1 machine, when I installed Journaley, the fonts and displayed widgets are incorrectly sized.

It looks like Journaley uses a fixed size font but widgets that scale with the size of the window (or something like that). Thus, the font size is far too large for the widgets. I didn't see any way to scale the font so it would fit into the widgets. 

Here is a screenshot of Journaley on this machine with the help-about screen shown
![journaleydisplayissuescreenshot](https://cloud.githubusercontent.com/assets/17343892/21067539/61ea3e5c-be31-11e6-82b5-71b3ac6f0f6a.jpg)

Here is the password dialog box. 
![image](https://cloud.githubusercontent.com/assets/17343892/21067616/0edaf70a-be32-11e6-89d9-b2d9ac1bc9c7.png)

Thanks,
Craig Lang

**Comment by yyoon** [comment]
Hi Craig. Thanks for reporting. I think this is the same issue as #113.
I discovered that I might need some significant rewrite of existing code to make this work properly, and I cannot easily find enough time to do that. Hopefully I could come back to this during the upcoming holiday season.

I'll close this issue, but please feel free to add to #113.
