### ISSUE TITLE
Improve Settings screen

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#38]
Rework UI/UX of the Settings Screen by trying to keep all settings related functions to one screen including password setting, journal entries location and appearance.

See [SettingsUI.png](https://www.pixelapse.com/sardonix/projects/Journaley/files/SettingsUI.png) for latest revision of UI. 

* Needs to allow for appearance changes
* Needs to allow for password enabling and changing
* Needs to allow for spell checker to be disabled and language picker
* Needs to allow for Journal DB location editing

**Comment by yyoon** [comment]
Unfortunately, I've learned that our spell checker only supports four specific languages: English, French, German, and Spanish.
(https://msdn.microsoft.com/en-us/library/system.windows.controls.spellcheck%28v=vs.100%29.aspx?f=255&MSPPError=-2147217396)

Anyways, the spell checker / password setting ui part is pretty much done. Only the update UI work is remaining (which doesn't look very easy..)

**Comment by yyoon** [comment]
Also, d2db7d8e75e2fc1c45901129e6ab1f039c72d8d3 this commit should fix the mouse cursor problem in the Settings UI.
