### ISSUE TITLE
Resizing window vertically and horizontally causes right sidebar to flash

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#47]
Seems to happen mostly just to the sidebar, don't know if we need to repaint it everytime its resized or what.

**Comment by yyoon** [comment]
Can you try now and see if the left entry list box flashes when resizing? I think 9cbd44e commit significantly reduced the flashing. It also doesn't flash much when editing an entry.

**Comment by sguergachi** [comment]
Its fixed!
