### ISSUE TITLE
Checking for updates

### ISSUE THREAD

**Issue by yyoon** [yyoon/Journaley#5]
Automatically check for a new release, and inform the user if there is on launching.

**Comment by yyoon** [comment]
This should work starting from 9d3439889303d6ee4e8ba2ea860d09432987fdd4.

Only the very basic auto-update logic has been added. When there is a new release found on the server, Journaley will download it behind the scenes, and then use the new version on the next launch.

Currently, there is no notification shown to the user whatsoever, and the app updates itself secretly.
@sguergachi, do you have any specific idea on what should happen on update?
(e.g., letting the user know there was an update, showing release notes to tell what new features were added, ...)

**Comment by sguergachi** [comment]
My thinking is the user has to accept the update. We can shouldn't automatically update in the background silently unless the user allows it. If we push a bad update that causes problems with entries, that's something we want to allow users to prevent. 

I'm not sure if Squirrel has some way of displaying a prompt UI to ask users if they would like to update and a way to display release notes hosted on github. But this could be a lot of work. 

To simplify things we could add to settings: Check and install updates automatically. 
And a button: Check for updates now.

this removes the need to create a whole new UI screen to prompt and for release notes we could just put a link to the where we would host release notes.

**Comment by yyoon** [comment]
Squirrel provides an API to only check for updates, so we could provide any kinds of UIs if we want.

How about showing the following three options as typical? (1) Install and relaunch, (2) Remind me later, (3) Skip this version.

By the way, I just discovered that Squirrel is messing up the jump list ("New Entry" menu shown when right-clicking the Journaley icon from the taskbar). I'll ask the Squirrel developers and see if there would be a workaround. Otherwise, maybe we should find some other installer..

**Comment by sguergachi** [comment]
I don't want us to have to do the extra work of creating the popup that ends up annoying users. I never understood the logic behind having the user double click your app icon with the intention of using your application and you decide to interrupt at that moment with a request to make them wait for your app to update.

I like the ability to update silently in the background. I just want to make sure we get user consent. And if the user doesn't want to give consent we allow them to manually check for updates in settings.

We could, as part of the welcome screen, ask the user if they wants to update in the background and have that also be a toggle in settings.

This way we don't annoy users every time they launch the app, and make sure we show a popup only when the user is requesting a check for update.

**Comment by yyoon** [comment]
Now the update logic / UI has been implemented. Currently, when Check for Update button is clicked, it shows a pop-up dialog saying one of the two messages.

1.  Journaley is already up to date!
2.  Journaley has been updated to v#.#.    
    Restart Journaley to use the new version.

These messages are hard-coded, so it should be easy to change them.

**Comment by sguergachi** [comment]
Looks awesome! Love how invisible it feels for it to update so fast in the background.

One detail: When the app checks for update the settings button changes to "Update Available" when you click it and perform the update the button should return to "Check for Update". Right now it only updates on a hover.

**Comment by sguergachi** [comment]
Also, we should add a label beside the check update button to show the current version for reference. 
I updated SettingsUI to reflect this.

**Comment by yyoon** [comment]
Fixed those two issues.

**Comment by sguergachi** [comment]
Version number needs to have Regular Segoe UI while Label needs to be Semibold.
