### ISSUE TITLE
Hovering over scrollable areas should make them focused to allow for mouse wheel scrolling

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#52]
i.e. I shouldn't have to click on the entry list box to get focus before I can scroll or the entry text area, hovering over these areas should automatically request focus on those component to allow me to use my mouse scroll wheel.

Of course this only occurs if the application window itself is already in focus.

**Comment by yyoon** [comment]
There's a problem with this. When a photo is popped out, the popup window immediately goes behind the main window, because the control under the mouse in the main window (the web browser) takes the focus immediately. I'll have to think about a workaround to this problem..
