### ISSUE TITLE
Ability to add image from Clipboard

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#73]
This would make life a lot easier. I don't like having to go to the file explorer every time I want to select a picture.

* If you take a screenshot of your desktop > you have to save the image and then open it in file explorer.
* If you want to add an image from a website > you have to save that image to your computer and then open it in file explorer

Implementation would be the following:

1. When image button is clicked > check clipboard for supported images
2. If supported images are in clipboard, show popup menu with both option to add from clipboard or to add from file explorer
3. If no supported images in clipboard, follow current behaviour of immediately opening the file explorer.

**Comment by yyoon** [comment]
Now this seems to work fine for me.
