### ISSUE TITLE
Journaley Website

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#74]
I'm currently investigating making a simple website for Journaley. Will likely be using a simple wordpess site for now.

The website would contain likely contain 2 to 3 pages:

1. Home Page >> Acts as the page explaining *what* Journaley is and tries to justify why you might want to write a journal.

2. About >> Explain who is behind Journaley and a paragraph justifying Journaley's existence. And finally provide ways to contact.

2. Dev Blog >> A way to communicate with users with progress and release notes etc.

**Comment by sguergachi** [comment]
We won't have a dev blog for now. Its a single page website that describes the app: http://yyoon.github.io/Journaley/

**Comment by yyoon** [comment]
This is really cool. I went through the screenshots and their descriptions, which look fine.

Would it be difficult to add a way to go to the prev/next screenshot? I find it a bit tedious to close the screenshot with the X button and manually select the next screenshot.

**Comment by sguergachi** [comment]
Not sure, that would require some JS work that I have no experience with. I built the site with the help of a template which had most of the current functionality built in.

But If I get the time to figure it out, i'll try.

**Comment by sguergachi** [comment]
bought www.journaleyapp.com which goes to the website now.

**Comment by sguergachi** [comment]
Added GoSquared analytics to the site

**Comment by sguergachi** [comment]
I think for now we can close this. Additions to the website can be made in the future, but it seems ok at this point.
