### ISSUE TITLE
Attempt to automatically locate DayOne entires folder in dropbox folder. 

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#8]
The app should first make an attempt at finding the Day One entries folder in the local dropbox folder by looking at possible locations. 

*Locating Dropbox folder (check whether the user even has a dropbox folder)
*Searching through dropbox folder for DayOne folder
*Selecting entry folder from located DayOne folder

**Comment by yyoon** [comment]
Let's merge this to #11.
