### ISSUE TITLE
The character " ` " doesn't render properly

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#81]
Not sure if this is a font problem, but when you type ` and then a letter after that, it isn't properly spaced out.

You can see the entry list box displays the character properly but the entry page doesn't.
![image](https://cloud.githubusercontent.com/assets/615386/8017010/d7e6f28e-0bb9-11e5-98d4-c4fc9c54edbe.png)

**Comment by yyoon** [comment]
Works fine for me... it's weird that the font looks a little bit different.
![image](https://cloud.githubusercontent.com/assets/1309817/8998618/ef0b0c66-376a-11e5-9ed1-66f0a61199ed.png)

**Comment by yyoon** [comment]
Now I see this problem occurring after doing #83.

It seems like the Noto Sans font is causing this problem. I don't think I have any control with this. Do you have any idea how to deal with this?

**Comment by sguergachi** [comment]
Maybe we can try Open Sans and see if it has the same issue.


-
Sammy Guergachi

**Comment by yyoon** [comment]
The same problem occurred when I set the font to Noto Sans in notepad.
I haven't changed the code yet, but I could confirm that this problem does not occur with Open Sans, using notepad.

Is this a serious problem, though? Frankly, I don't want to go through the hassle of changing all the Noto Sans reference to Open Sans in our code and resources for now.

**Comment by sguergachi** [comment]
Nope. This is definitely low priority. Will remove from milestone but keep open in case we find an updated Noto Font or if people complain about this. 

-Sammy Guergachi
On 8/2/2015 9:52:57 AM, YoungSeok Yoon <notifications@github.com> wrote:
The same problem occurred when I set the font to Noto Sans in notepad.
I haven't changed the code yet, but I could confirm that this problem does not occur with Open Sans, using notepad.
Is this a serious problem, though? Frankly, I don't want to go through the hassle of changing all the Noto Sans reference to Open Sans in our code and resources for now.

**Comment by yyoon** [comment]
Sounds reasonable to me.

**Comment by crxtrdude** [comment]
Well, programmers who use backticks for storing their scribbled code over Journaley might have a problem with it, but as Sammy said it's not a priority unless someone would ever complain with it.

BTW, there is the other way to do preformatting text like `<code>` or tabbing (aka Inserting four spaces). They work on the current MarkdownSharp implementation you guys are using.

EDIT: I've just downloaded Noto Sans recently, the backticks are fixed. Set it on Notepad:
![Sample](http://i.imgur.com/a7QnhdM.png)
