### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by hattiewei** [yyoon/Journaley#84]
I got the following error: 
unhandled exception has occured in your application. if you click continue, the applicaiton will ingore this error and attempt to continue. if you click quit, the applicaiton will close immediately. 
could not find a part of the path: 'C:\user\owner\dropbox\entries. 
please help. 

when trying to set up a dropbox path for syncing, do i need to create subfolders under Dropbox? Thanks. 
Hattie

**Comment by yyoon** [comment]
@hattiewei Which version of Journaley did you install? 1.4?
Also, are you already using Day One, or are you just trying to use Journaley without Day One?

**Comment by hattiewei** [comment]
Hi, I installed 1.4. I use day one on my iphone and iPad. Obvious it is not currently on my windows PC. I guess there is a missing link somewhere? Thanks for your help.

**Comment by sguergachi** [comment]
If you are syncing to dropbox with Day One, the entries should be located under: Dropbox/Apps/Day One/Journal.dayone/entires/

Make sure you don't have Day One syncing using iCloud.

**Comment by hattiewei** [comment]
Thanks. I did that and the folder does appear. But I cannot go back to the initial set up window popup for the dropbox folder any more even after I uninstall and reinstall a few times. So I am still getting the same error message. Any idea how to fix that? Really appreciate your help.

**Comment by hattiewei** [comment]
Thanks. It works now. Awesome tool.

**Comment by sguergachi** [comment]
Great! Let us know if you run into any other issues.
