### ISSUE TITLE
Add about page

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#86]
We need a page accessible from settings screen to contain:
- Credits
- License for Journaley
- License for any open source stuff we use
- Link to the site and or the github page

The about page is accessed through the settings screen. An about button will toggle between the settings screen and the about screen.

**Comment by sguergachi** [comment]
License links
Noto Sans: http://www.apache.org/licenses/LICENSE-2.0.html
Another Month Calendar: http://www.codeproject.com/info/cpol10.aspx
MarkdownSharp: http://opensource.org/licenses/mit-license.php
Squirrel.Windows: https://github.com/Squirrel/Squirrel.Windows/blob/master/COPYING

**Comment by sguergachi** [comment]
AboutUI.png is updated to contain everything mentioned.

**Comment by yyoon** [comment]
I just linked our names to our GitHub profile pages. If you want your name to link to another homepage, you can change it from the source code. (SettingsForm.cs:112)
