### ISSUE TITLE
Add subtle fade in for images in listbox entry being loaded in async

### ISSUE THREAD

**Issue by sguergachi** [yyoon/Journaley#88]
Fade in of images in listbox entry to be a little less jarring than suddenly appearing. This relates to the changes made in #22. Assuming this adds little overhead, animation should be 400ms and tweakable from there.

This might help for implementation: http://stackoverflow.com/questions/960738/fading-out-an-image-with-transparency-in-winforms-ui-net3-5

**Comment by yyoon** [comment]
The `FadeInTime` can be adjusted in the `Journaley\Controls\EntryListBox.cs` file.
